name: Build unsigned debug apk

on:
  workflow_dispatch

jobs:
  pre_build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11.0.14+101'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permissions for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew build

  unit_tests:
    needs: [pre_build]
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v2
      - name: Grant execute permissions for gradlew
        run: chmod +x gradlew
      - name: Run Unit Tests
        run: ./gradlew test

  android_tests:
    needs: [pre_build]
    runs-on: [macos-latest]
    steps:
      - uses: actions/checkout@v2
      - name: Grant execute permissions for gradlew
        run: chmod +x gradlew
      - name: Run Instrumentation Tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 29
          script: ./gradlew connectedAndroidTest

  build_apk:
    needs: [unit_tests, android_tests, pre_build]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2
        
      - name: Grant execute permissions for gradlew
        run: chmod +x gradlew
        
      - name: Build unsigned debug apk
        run: ./gradlew assembleDebug

      - name: Upload debug apk
        uses: actions/upload-artifact@v2
        with:
          name: apk-debug
          path: app/build/outputs/apk/debug