name: Build project

on:
  push:
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'zulu'
        cache: gradle

    - name: Grant execute permissions for gradlew
      run: chmod +x gradlew
    - name: Build project with Gradle
      run: ./gradlew build
    - name: Upload logs
      uses: actions/upload-artifact@v4
      with:
        name: lint-logs
        path: app/build/reports/lint-results-debug.html
